language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

services: mysql

before_script:
  - mysql -e 'create database pmt;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install -n --dev --prefer-source

script: phpunit -c app
